package com.henry.fakeingresso.domain.model

data class Movie(
    val id: String = "",
    val ancineId: String = "",
    val cast: String = "",
    val city: String = "",
    val completeTags: List<CompleteTag>? = null,
    val contentRating: String = "",
    val countIsPlaying: Int = 0,
    val countryOrigin: String = "",
    val creationDate: String = "",
    val director: String = "",
    val directors: String = "",
    val distributor: String = "",
    val duration: String = "",
    val genres: List<String> = emptyList(),
    val imageFeatured: String = "",
    val images: List<Image> = emptyList(),
    val inPreSale: Boolean = false,
    val isComingSoon: Boolean = false,
    val isPlaying: Boolean = false,
    val isReexhibition: Boolean = false,
    val movieIdUrl: String = "",
    val nationalSiteURL: String = "",
    val originalTitle: String = "",
    val premiereDate: PremiereDate,
    val priority: Int = 0,
    val rating: Double = 0.0,
    val ratingDescriptors: List<String> = emptyList(),
    val ratingDetails: RatingDetails? = null,
    val siteURL: String = "",
    val synopsis: String = "",
    val tags: List<String> = emptyList(),
    val title: String = "",
    val trailers: List<Trailer> = emptyList(),
    val type: String= "",
    val urlKey: String = ""
)